/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#313030",
        "surface-container-high": "#eae7e7",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#e9c339",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#26dbe7",
        "primary-fixed": "#ffe07e",
        "surface-container-low": "#f6f3f2",
        "surface-bright": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "outline-variant": "#d0c6ae",
        "on-background": "#1c1b1b",
        outline: "#7e7662",
        "secondary-container": "#ede3bb",
        "on-primary-container": "#735e00",
        "inverse-on-surface": "#f3f0ef",
        "surface-tint": "#725c00",
        primary: "#725c00",
        "tertiary-container": "#4cf0fd",
        secondary: "#655e40",
        "secondary-fixed": "#ede3bb",
        "secondary-fixed-dim": "#d0c7a1",
        "on-primary-fixed-variant": "#564500",
        "on-primary-fixed": "#231b00",
        "on-secondary-fixed-variant": "#4d472a",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#004f54",
        "surface-container-highest": "#e5e2e1",
        "on-error-container": "#93000a",
        "primary-container": "#ffd84d",
        "inverse-primary": "#e9c339",
        "on-surface-variant": "#4d4634",
        "on-tertiary-container": "#006b71",
        error: "#ba1a1a",
        "tertiary-fixed": "#7bf4ff",
        "on-primary": "#ffffff",
        "surface-container": "#f0eded",
        "on-error": "#ffffff",
        "on-surface": "#1c1b1b",
        "surface-dim": "#dcd9d9",
        "on-tertiary-fixed": "#002022",
        background: "#fcf9f8",
        tertiary: "#006970",
        "on-secondary-container": "#6c6445",
        surface: "#fcf9f8",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#201c04",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1.5rem",
        "3xl": "2.5rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "section-padding-mobile": "64px",
        "section-padding-desktop": "120px",
        gutter: "24px",
        "container-max": "1200px",
      },
      fontFamily: {
        "display-hero": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-hero-mobile": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": [
          "72px",
          {
            lineHeight: "1.1",
            letterSpacing: "-0.04em",
            fontWeight: "700",
          },
        ],
        "body-md": [
          "16px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        "headline-lg": [
          "48px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "display-hero-mobile": [
          "40px",
          {
            lineHeight: "1.2",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "headline-md": [
          "32px",
          {
            lineHeight: "1.3",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" },
        ],
      },
    },
  },
  plugins: [],
};
